play = ["재생", 'play', 'p']
stop = ["정지", "stop", "st"]
volume = ["볼륨", "음량", "volume", "v"]
autoplay = ["추천영상", "autoplay", "auto"]
nowplay = ["현재재생", "np", "nowplay", "nowplaying"]
queue = ["대기열", "queue", "q"]
skip = ["스킵", "skip"]